package resource_test

import (
	"testing"
	"time"

	resource "github.com/concourse/time-resource"
	. "github.com/onsi/ginkgo"
	. "github.com/onsi/gomega"
	"github.com/onsi/gomega/gexec"
)

var _ = BeforeSuite(func() {
	actualNow := time.Now().UTC()
	// The "current" time must be after 03:57 to satisfy the offset generated by empty environmental variables
	mockNow := time.Date(actualNow.Year(), actualNow.Month(), actualNow.Day(), 7, 26, 0, 0, actualNow.Location())
	resource.GetCurrentTime = func() time.Time {
		return mockNow
	}
})

var _ = AfterSuite(func() {
	gexec.CleanupBuildArtifacts()
})

func TestTimeResource(t *testing.T) {
	RegisterFailHandler(Fail)
	RunSpecs(t, "Time Resource Suite")
}
