#!/bin/sh -ex

export GOPATH=$PWD/gopath
export PATH=$GOPATH/bin:$PATH

export BUILD_DIR=$PWD/built-resource
cd $GOPATH/src/github.com/concourse/time-resource

export GOPATH=${PWD}/Godeps/_workspace:$GOPATH
export PATH=${PWD}/Godeps/_workspace/bin:$PATH

go install github.com/onsi/ginkgo/ginkgo

mkdir -p assets
go build -o assets/in in/main.go
go build -o assets/check check/main.go
go build -o assets/out out/main.go

cp -a assets/ Dockerfile $BUILD_DIR
